language: java

services:
  - docker

sudo: false

install: true

script:
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent package
  - docker build . -t cyanelix/monitor

cache:
    directories:
        - '$HOME/.m2/repository'

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push cyanelix/monitor;
    fi
