---
monitored:
  checks:
    - url: http://example.com
      method: HEAD
      expectedStatus: OK
      recipients: to@example.com
    - url: http://www.example.com
      method: GET
      expectedStatus: OK
      recipients: to@example.com
    - url: http://localhost/foo
      method: POST
      expectedStatus: OK
      recipients:
        - to@example.com

digest:
  recipients: digest@example.com

logging:
  level:
    com:
      cyanelix: debug

spring:
  mail:
    host: smtp.example.com
